# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='price',
            field=models.IntegerField(default=7),
        ),
    ]
