# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shirt_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='desc',
            field=models.CharField(default='No description available', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shirt',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
